DEBUG 2020-04-24 11:19:54.019 UTC: 	 Running on: Linux cmslpc27.fnal.gov 2.6.32-754.28.1.el6.x86_64 #1 SMP Wed Mar 11 12:07:33 CDT 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux Fermi release 6.10 (Ramsey)
DEBUG 2020-04-24 11:19:54.037 UTC: 	 OpenSSl version: OpenSSL 1.0.1e-fips 11 Feb 2013
DEBUG 2020-04-24 11:19:54.038 UTC: 	 Executing command: 'submit'
DEBUG 2020-04-24 11:19:54.050 UTC: 	 Found CRAB cache file /uscms/home/twelton/.crab3
DEBUG 2020-04-24 11:19:54.060 UTC: 	 Checking credentials
DEBUG 2020-04-24 11:19:54.061 UTC: 	 Found proxy file /uscms/home/twelton/x509up_u54539
DEBUG 2020-04-24 11:19:54.061 UTC: 	 Getting proxy life time left
DEBUG 2020-04-24 11:19:54.165 UTC: 	 Executing : 
 command : voms-proxy-info -file /uscms/home/twelton/x509up_u54539 -timeleft
 output : 5624

 error: 
 retcode : 0
DEBUG 2020-04-24 11:19:54.269 UTC: 	 Executing : 
 command : voms-proxy-info -file /uscms/home/twelton/x509up_u54539 -actimeleft
 output : 5624

 error: 
 retcode : 0
DEBUG 2020-04-24 11:19:54.269 UTC: 	 Proxy valid for 01:33:44 hours
INFO 2020-04-24 11:19:54.270 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-04-24 11:19:54.270 UTC: 	 Loading CRAB configuration file.
ERROR 2020-04-24 11:19:57.102 UTC: 	 Error while loading CRAB configuration:
Failed to retrieve username from SiteDB. Your DN does not seem to be registered in SiteDB.
Details follow:
  Executed command: curl -sS --capath /etc/grid-security/certificates --cert /uscms/home/twelton/x509up_u54539 --key /uscms/home/twelton/x509up_u54539 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
    Stdout:
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
      <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
       <head>
       <title>CMSWEB Error: No such site</title>
       <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
       <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
       <link rel="stylesheet" type="text/css" media="screen" href="/css/cmsweb.css" />
      </head>
      <body>
       <div id="main">
        <div id="top">
         <div class="boxTitle"><img src="/img/title.gif" alt="CMSWEB (title)" /></div>
        </div>
        <div id="middle">
         <div class="boxLinkContainer">
          <h2>No such site</h2>
          <p>The site you requested does not exist. Could we interest you in <a href='/'>anything else</a>?</p>
         </div>
        </div>
        <div id="bottom">
         <div class="boxFooter">&nbsp;</div>
        </div>
       </div>
      </body>
      </html>
      
    Parsed username: 
Note: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-04-24 11:19:57.102 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Failed to retrieve username from SiteDB. Your DN does not seem to be registered in SiteDB.
Details follow:
  Executed command: curl -sS --capath /etc/grid-security/certificates --cert /uscms/home/twelton/x509up_u54539 --key /uscms/home/twelton/x509up_u54539 'https://cmsweb.cern.ch/sitedb/data/prod/whoami'
    Stdout:
      <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
      <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
       <head>
       <title>CMSWEB Error: No such site</title>
       <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
       <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
       <link rel="stylesheet" type="text/css" media="screen" href="/css/cmsweb.css" />
      </head>
      <body>
       <div id="main">
        <div id="top">
         <div class="boxTitle"><img src="/img/title.gif" alt="CMSWEB (title)" /></div>
        </div>
        <div id="middle">
         <div class="boxLinkContainer">
          <h2>No such site</h2>
          <p>The site you requested does not exist. Could we interest you in <a href='/'>anything else</a>?</p>
         </div>
        </div>
        <div id="bottom">
         <div class="boxFooter">&nbsp;</div>
        </div>
       </div>
      </body>
      </html>
      
    Parsed username: 
[1mNote[0m: Make sure you have the correct certificate mapped in SiteDB (you can check what is the certificate you currently have mapped in SiteDB by searching for your name in https://cmsweb.cern.ch/sitedb/prod/people). For instructions on how to map a certificate in SiteDB, see https://twiki.cern.ch/twiki/bin/viewauth/CMS/SiteDBForCRAB.
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-04-27 09:19:29.807 UTC: 	 Running on: Linux cmslpc27.fnal.gov 2.6.32-754.28.1.el6.x86_64 #1 SMP Wed Mar 11 12:07:33 CDT 2020 x86_64 x86_64 x86_64 GNU/Linux - Scientific Linux Fermi release 6.10 (Ramsey)
DEBUG 2020-04-27 09:19:29.827 UTC: 	 OpenSSl version: OpenSSL 1.0.1e-fips 11 Feb 2013
DEBUG 2020-04-27 09:19:29.828 UTC: 	 Executing command: 'submit'
DEBUG 2020-04-27 09:19:29.828 UTC: 	 Found CRAB cache file /uscms/home/twelton/.crab3
DEBUG 2020-04-27 09:19:29.835 UTC: 	 Checking credentials
DEBUG 2020-04-27 09:19:29.835 UTC: 	 Found proxy file /uscms/home/twelton/x509up_u54539
DEBUG 2020-04-27 09:19:29.835 UTC: 	 Getting proxy life time left
DEBUG 2020-04-27 09:19:29.940 UTC: 	 Executing : 
 command : voms-proxy-info -file /uscms/home/twelton/x509up_u54539 -timeleft
 output : 86313

 error: 
 retcode : 0
DEBUG 2020-04-27 09:19:30.045 UTC: 	 Executing : 
 command : voms-proxy-info -file /uscms/home/twelton/x509up_u54539 -actimeleft
 output : 86313

 error: 
 retcode : 0
DEBUG 2020-04-27 09:19:30.045 UTC: 	 Proxy valid for 23:58:33 hours
INFO 2020-04-27 09:19:30.045 UTC: 	 Will use CRAB configuration file crab_cfg.py
DEBUG 2020-04-27 09:19:30.045 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-04-27 09:19:30.057 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-04-27 09:19:30.058 UTC: 	 Working area '/uscms_data/d3/twelton/WorkingArea/CMSSW_10_2_16/src/PhysicsTools/NanoAODTools/crab/crab_projects/crab_MuTau2018D' already exists 
Please change the requestName in the config file
ERROR 2020-04-27 09:19:30.058 UTC: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/bin/crab", line 145, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 324, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.2001/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 418, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/twelton/WorkingArea/CMSSW_10_2_16/src/PhysicsTools/NanoAODTools/crab/crab_projects/crab_MuTau2018D' already exists 
Please change the requestName in the config file
